version: "3.8"
services:
  web:
    build: .
    command: "gunicorn -b 0.0.0.0:8000 app:app"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=production